services:
  - type: web
    name: cms-landing
    runtime: static
    rootDir: landing
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: cms-staff
    runtime: static
    rootDir: staff
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_INSTITUTE_NAME
        value: Al-Hamd Science College
      - key: VITE_INSTITUTE_TAG
        value: Excellence in Education

  - type: web
    name: cms-student
    runtime: static
    rootDir: student
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_INSTITUTE_NAME
        value: Al-Hamd Science College
      - key: VITE_INSTITUTE_TAG
        value: Excellence in Education
